#!/bin/bash

# Copyright (c) 2018, Ben Blum
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ "`pwd | sed 's/.*\///'`" != "pebsim" ]; then
	echo -e "\033[01;31m$0 must be run from the pebsim directory.\033[00m"
	exit 1
fi

export QUICKSAND_CONFIG_STATIC="$1"
if [ ! -z "$2" ]; then
	export QUICKSAND_CONFIG_DYNAMIC="$2"
	# must be an absolute path for c code to see it
	# it will be removed by c code after the attribute is set
	export QUICKSAND_CONFIG_TEMP=`mktemp /dev/shm/landslide-dynamic-pps.XXXXXXXX`
else
	export QUICKSAND_CONFIG_DYNAMIC=
fi

export LANDSLIDE_CONFIG=config.landslide

# FIXME: Gross hack
if ! grep "PINTOS_KERNEL=1" "$LANDSLIDE_CONFIG" >/dev/null; then
	# Pebbles.
	export KERNEL_SOURCE_DIR="`grep KERNEL_SOURCE_DIR $LANDSLIDE_CONFIG | cut -d= -f2-`"
fi

export DISPLAY=
./build.sh && time echo c | ../install/bin/bochs -q
